const ADD_CHARACTER_FAV = 'ADD_CHARACTER_FAV';
const DELETE_CHARACTER_FAV = 'DELETE_CHARACTER_FAV';
const FILTER = 'FILTER';
const ORDER = 'ORDER'

module.exports = {
    ADD_CHARACTER_FAV,
    DELETE_CHARACTER_FAV,
    FILTER,
    ORDER
}